#logging:
#  level:
#    root: warn
#    com.memorynotfound: INFO
#    org.springframework.web: INFO
#    org.springframework.security: INFO

server:
  port: 8080

# custom configuration app
xenon:
  configurations:
    themeleaf:
      cache: false
    datasource:
      driver: ~
      url: ~
      username: ~
      password: ~
    avatar:
      url: ~
    redis:
      host: ~
      port: 0
    email:
      host: ~
      port: 0
      protocol: ~
      username: ~
      password: ~
      auth: false
      tls:
        enable: false
        required: false

# Base configuration app
spring:
  liquibase:
    change-log: classpath:/db/changelog/databaseChangelog.xml
    database-change-log-table: AD_DB_CHANGELOG
    database-change-log-lock-table: AD_DB_CHANGELOG_LOCK
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2KB
  thymeleaf:
    cache: ${xenon.configurations.themeleaf.cache}
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    driverClassName: ${xenon.configurations.datasource.driver}
    url: ${xenon.configurations.datasource.url}
    username: ${xenon.configurations.datasource.username}
    password: ${xenon.configurations.datasource.password}
    continueOnError: true
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
    initialization-mode: always
    jpa:
      show-sql: true
  mail:
    host: ${xenon.configurations.email.host}
    username: ${xenon.configurations.email.username}
    password: ${xenon.configurations.email.password}
    properties:
      email:
        transport:
          protocol: ${xenon.configurations.email.protocol}
        smtp:
          port: ${xenon.configurations.email.port}
          auth: ${xenon.configurations.email.auth}
          starttls:
            enable: ${xenon.configurations.email.tls.enable}
            required: ${xenon.configurations.email.tls.required}

